version: '3.3'

services:
  # Adminer database GUI
  # Alternatives to Adminer include phpMyAdmin and MySQL Workbench 
  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - 8081:8080
    environment:
      ADMINER_DESIGN: nette
