version: '3'

services:
  web:
    image: nginx:1.19-alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ../www/:/var/www/html/public/
      - ../nginx/conf.d/http.conf:/etc/nginx/conf.d/default.conf
      - ../nginx/log/:/var/log/nginx/
      - ../letsencrypt/etc:/etc/letsencrypt/
    environment:
      DOMAIN: ${DOMAIN}
