version: '3.3'

services:
  db:
    image: mysql:8.0.16
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /home/obe/Documents/dev/docker/mysql/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example

  # Alternatives to Adminer are phpMyAdmin and MySQL Workbench 
  admin:
    image: adminer:4.7.1-standalone
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DESIGN: nette
