version: '3'

services:
  web:
    image: nginx:1.19-alpine
    ports:
      - "80:80"
    volumes:
      - ../nginx/http.conf:/etc/nginx/conf.d/default.conf
      - ../www/:/usr/share/nginx/html/
    environment:
      DOMAIN: ${DOMAIN}
  